--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/cpott/Pictures/wallpapers/wp13849744-fujiwara-tofu-shop-wallpapers.jpg"

-- Special
background="#0d0a09"
foreground="#d7c5a3"
cursor="#d7c5a3"

-- Colors
color0="#0d0a09"
color1="#4B3018"
color2="#4C3726"
color3="#674D2E"
color4="#4C4E49"
color5="#93683A"
color6="#77846C"
color7="#d7c5a3"
color8="#968972"
color9="#4B3018"
color10="#4C3726"
color11="#674D2E"
color12="#4C4E49"
color13="#93683A"
color14="#77846C"
color15="#d7c5a3"
