#!/bin/bash

CONFIG_FILES="/home/cpott/.config/waybar/config /home/cpott/.config/waybar/style.css"

trap "killall waybar" EXIT

while true; do
    waybar &
    inotifywait -e create,modify $CONFIG_FILES
    killall waybar
done
